sudo: required
services:
  - docker

script:
  - docker build -t tyl13r/nodeSimple .
  - docker images tyl13r/nodesSimple

before_deploy:
  - docker login -u tyl13r -p="$PASSWORD_DOCKER"

deploy:
  skip_cleanup: true
  provider: script
  script: docker push tyl13r/DockerTravisCi
  on:
    branch: main
