sudo: required
services:
  - docker

script:
  - docker build -t tyl13r/docker-travis-ci .
  - docker images tyl13r/docker-travis-ci

before_deploy:
  - docker login -u tyl13r -p="$PASSWORD_DOCKER"

deploy:
  skip_cleanup: true
  provider: script
  script: docker push tyl13r/docker-travis-ci
  on:
    branch: main
